language: julia
os:
  - linux
  - osx

julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: DrKrar@live.com
  
 after_success:
    - julia -e 'cd(Pkg.dir("GeoEfficiency")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; 

