language: julia
os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.1
  - nightly
notifications:
 
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl pdf clean
      after_success: skip

after_success:
    - julia -e 'try Pkg.dir; catch err; using Pkg; end; 
                cd(Pkg.dir("GeoEfficiency")); 
                Pkg.add("Coverage"); using Coverage; 
                Coveralls.submit(Coveralls.process_folder());
                Codecov.submit(Codecov.process_folder());'
