language: julia
os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.1
  - nightly
notifications:
 
  
after_success:
    - julia -e 'try Pkg.dir; catch err; using Pkg; end'
    - julia -e 'cd(Pkg.dir("GeoEfficiency")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; 
    - julia -e 'cd(Pkg.dir("GeoEfficiency")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

