site_name:        GeoEfficiency.jl
repo_url:         https://github.com/DrKrar/ GeoEfficiency.jl
site_description: Acurate geometrical efficiency calculator
site_author:      Mohamed E. Krar

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: build/index.md
  - Mauual: 
    - About: build/manual/GeoEfficiency.md
    - Physics_Model: build/manual/Physics_Model.md
    - Calculations: build/manual/Calculations.md
    - Output_Interface: build/manual/Output_Interface.md
    - Input_Batch: build/manual/Input_Batch.md
  - Development: build/manual/Development.md
  - Index: build/list.md
