environment:
  matrix:
    - JULIA_VERSION: "v0.4"
        ARCH: x86
        JULIA_URL: "julialang/bin/winnt/x86/0.4/julia-0.4-latest-win32.exe"
    - JULIA_VERSION: "v0.4"
        ARCH: x64
        JULIA_URL: julialang/bin/winnt/x64/0.4/julia-0.4-latest-win64.exe
    - JULIA_VERSION: "v0.5"
        ARCH: x86
        JULIA_URL: "julianightlies/bin/winnt/x86/julia-latest-win32.exe"
    - JULIA_VERSION: "v0.5"
        ARCH: x64
        JULIA_URL: "julianightlies/bin/winnt/x64/julia-latest-win64.exe"

notifications:         
  - provider: Email
		on_build_success: false
		on_build_failure: true
		on_build_status_changed: true
	
install:
  - ps: (new-object net.webclient).DownloadFile(
              $("http://s3.amazonaws.com/"+$env:JULIA_URL),
              "C:\projects\julia-installer.exe"
        )
  - C:\projects\julia-installer.exe /S /D=C:\projects\julia

build_script:
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo(); Pkg.clone(pwd(), \"GeoEfficiency\"); Pkg.build(\"Geoefficiency\")"
  - cd C:\Users\appveyor\.julia\%JULIA_VERSION%\GeoEfficiency\
  - type deps\deps.jl

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"GeoEfficiency\")"
  - cd C:\Users\appveyor\.julia\%JULIA_VERSION%\GeoEfficiency\
  - type test\GeoEfficiency.log
	